### ISSUE TITLE
加一个视觉仓库

### ISSUE THREAD

**Issue by pitlst** [DJTU-RM-TOE/DJTU-RM-TOE.github.io#5]
那个我是之前实验室的视觉，孙闻崎，我看github上还有我们实验室之前的视觉仓库还有我写的没有加到文档里，看看这一届的负责人能不能加进去，我现在已经没有联系了
https://github.com/pitlst/TOE-yolov7-obb-robomaster2023 大幅训练程序
https://github.com/pitlst/toe_aimbot_2023 自瞄程序

**Comment by pitlst** [comment]
还有一个很久以前的
https://github.com/SEU-SuperNova-CVRA/Robomaster2018-SEU-OpenSource

**Comment by evencewu** [comment]
已阅，添加完毕
